require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/bundle/**/*"
    - "db/schema.rb"
    - ".simplecov"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "app/admin/**/*"
    - "config/environments/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/EndOfLine:
  Enabled: False

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false